version: "2"
services:
    nginx1.14: 
        image: nginx:1.14
        ports:
           - 80:80
        links:
           - php7.2.6
        depends_on:
           - mysql5.6.40
           - php7.2.6
           - redis
        volumes:
           - ./www:/usr/share/nginx/html
           - ./nginx/conf.d:/etc/nginx/conf.d
           - ./nginx/nginx.conf:/etc/nginx/nginx.conf
           - ./nginx/logs:/var/log/nginx
        container_name: nginx1.14
        restart: always
    mysql5.6.40: 
        image: mysql:5.6.40
        environment: 
            TZ: 'Asia/Shanghai' 
            MYSQL_ROOT_PASSWORD: "root"
        expose:
            - 3306
        ports: 
            - 13306:3306
        volumes: 
            - ./mysql/conf:/etc/mysql
            - ./mysql/data:/usr/data
            - ./mysql/logs:/var/log/mysql
        container_name: mysql5.6.40
        restart: always
    php7.2.6: 
        image: "lihq1403/php:7.2.6-fpm"
        build: ./php
        links:
           - mysql5.6.40
           - redis
        expose:
            - 9000
        volumes:
            - ./www:/usr/local/nginx/html
            - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: php7.2.6-fpm
        restart: always
    redis:
        image: "lihq1403/redis:latest"
        build: ./redis
        volumes: 
            - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        ports: 
            - 16379:6379
        container_name: redis
        restart: always
         
  
